/*
 * Traffic Simulator
 *
 * Copyright (C) 2018, Ajuntament de Sant Feliu de Llobregat
 *
 * This program is licensed and may be used, modified and redistributed under
 * the terms of the European Public License (EUPL), either version 1.1 or (at
 * your option) any later version as soon as they are approved by the European
 * Commission.
 *
 * Alternatively, you may redistribute and/or modify this program under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either  version 3 of the License, or (at your option)
 * any later version.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the licenses for the specific language governing permissions, limitations
 * and more details.
 *
 * You should have received a copy of the EUPL1.1 and the LGPLv3 licenses along
 * with this program; if not, you may find them at:
 *
 *   https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 *   http://www.gnu.org/licenses/
 *   and
 *   https://www.gnu.org/licenses/lgpl.txt
 */
package org.santfeliu.trafsim;

/**
 *
 * @author realor
 */
public class LocationDialog extends javax.swing.JDialog
{
  private boolean accepted = false;


  /**
   * Creates new form LocationDialog
   */
  public LocationDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
  }

  public boolean showDialog()
  {
    pack();
    setLocationRelativeTo(getParent());
    setVisible(true);
    return accepted;
  }

  public void setLocationName(String name)
  {
    nameTextField.setText(name);
  }

  public String getLocationName()
  {
    return nameTextField.getText();
  }

  public void setLocationLabel(String label)
  {
    labelTextField.setText(label);
  }

  public String getLocationLabel()
  {
    return labelTextField.getText();
  }

  public void setOrigin(boolean origin)
  {
    originRadioButton.setSelected(origin);
    destinationRadioButton.setSelected(!origin);
  }

  public boolean isOrigin()
  {
    return originRadioButton.isSelected();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    centerPanel = new javax.swing.JPanel();
    nameLabel = new javax.swing.JLabel();
    nameTextField = new javax.swing.JTextField();
    labelLabel = new javax.swing.JLabel();
    labelTextField = new javax.swing.JTextField();
    typePanel = new javax.swing.JPanel();
    destinationRadioButton = new javax.swing.JRadioButton();
    originRadioButton = new javax.swing.JRadioButton();
    southPanel = new javax.swing.JPanel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/santfeliu/trafsim/resources/TrafficSimulator"); // NOI18N
    setTitle(bundle.getString("dialog.location.title")); // NOI18N

    centerPanel.setPreferredSize(new java.awt.Dimension(200, 100));
    centerPanel.setLayout(new java.awt.GridBagLayout());

    nameLabel.setText(bundle.getString("dialog.locations.name")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    centerPanel.add(nameLabel, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    centerPanel.add(nameTextField, gridBagConstraints);

    labelLabel.setText(bundle.getString("dialog.locations.label")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    centerPanel.add(labelLabel, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    centerPanel.add(labelTextField, gridBagConstraints);

    destinationRadioButton.setSelected(true);
    destinationRadioButton.setText(bundle.getString("dialog.locations.destination")); // NOI18N
    destinationRadioButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        destinationRadioButtonActionPerformed(evt);
      }
    });
    typePanel.add(destinationRadioButton);

    originRadioButton.setText(bundle.getString("dialog.locations.origin")); // NOI18N
    originRadioButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        originRadioButtonActionPerformed(evt);
      }
    });
    typePanel.add(originRadioButton);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    centerPanel.add(typePanel, gridBagConstraints);

    getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

    okButton.setText(bundle.getString("dialog.ok")); // NOI18N
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });
    southPanel.add(okButton);

    cancelButton.setText(bundle.getString("dialog.cancel")); // NOI18N
    cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelButtonActionPerformed(evt);
      }
    });
    southPanel.add(cancelButton);

    getContentPane().add(southPanel, java.awt.BorderLayout.PAGE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
  {//GEN-HEADEREND:event_okButtonActionPerformed
    accepted = true;
    dispose();
  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
  {//GEN-HEADEREND:event_cancelButtonActionPerformed
    dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void destinationRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_destinationRadioButtonActionPerformed
  {//GEN-HEADEREND:event_destinationRadioButtonActionPerformed
    destinationRadioButton.setSelected(true);
    originRadioButton.setSelected(false);
  }//GEN-LAST:event_destinationRadioButtonActionPerformed

  private void originRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_originRadioButtonActionPerformed
  {//GEN-HEADEREND:event_originRadioButtonActionPerformed
    destinationRadioButton.setSelected(false);
    originRadioButton.setSelected(true);
  }//GEN-LAST:event_originRadioButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JPanel centerPanel;
  private javax.swing.JRadioButton destinationRadioButton;
  private javax.swing.JLabel labelLabel;
  private javax.swing.JTextField labelTextField;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JButton okButton;
  private javax.swing.JRadioButton originRadioButton;
  private javax.swing.JPanel southPanel;
  private javax.swing.JPanel typePanel;
  // End of variables declaration//GEN-END:variables
}
